config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import messages
from django.shortcuts import redirect


def protected_file(request, path, document_root=None):
    messages.error(request, "접근 불가")
    print(request)
    return redirect('/')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

# if settings.DEBUG:
#     # 개발 서버로 실행 중 일떄 설정된 곳으로 접근하는 요청을 처리하기 위한 설정 // 미디어 파일을 로컬 pc 에 저장할 수 있고 직접 관리, 접근할 수 있으면 사용하지 않아도 무관함,
#     urlpatterns += static(settings.MEDIA_URL, protected_file, document_root=settings.MEDIA_ROOT)  # media 경로 추가 // 사용자가 업로드한 파일들을 개발 서버에서 확인할 수 있게 해줌
#     # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # media 경로 추가 // 사용자가 업로드한 파일들을 개발 서버에서 확인할 수 있게 해줌

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views

app_name = 'pybo'  # pybo 앱 이외의 다른 앱이 프로젝트에 추가 될 때, 동일한 url 별칭을 사용하지 않기 위한 방법
urlpatterns = [
    # base_views.py
    path('',
         base_views.index, name='index'),
    path('<int:question_id>/',
         base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/',
         question_views.question_vote, name='question_vote'),
    path('question/download/<int:question_id>/',
         question_views.question_file_download, name='question_file_download'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/',
         answer_views.answer_vote, name='answer_vote'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/',
         comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
         comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
         comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/',
         comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/',
         comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/',
         comment_views.comment_delete_answer, name='comment_delete_answer'),
]

pybo/forms.py
from django import forms
from pybo.models import Question, Answer, Comment


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content', 'file', 'filename']  # QuestionForm 에서 사용할 Question 모델의 속성
        labels = {
            'subject': '제목',
            'content': '내용',
            'file': '파일',
            'filename': '파일이름'
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변 내용',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글 내용',
        }

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer


# 생성
@login_required(login_url='common:login')  # @login_required 데코레이터 // login url 지정 // 로그아웃 상태에서 질문/답변을 등록하면 자동으로 로그인 화면으로 이동함.
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장 => 로그인이 필요한 함수인 것을 알 수 있음
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)


# 삭제
@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    print(answer)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)


# 수정
@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('pybo:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)


@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('pybo:detail', question_id=answer.question.id)

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from ..models import Question


def index(request):
    """
        ORM (Object-Relational Mapping) => Django Class 와 Database Data 를 연결 해주는 것 즉 Question.objects 에서 objects 가 연결해주는 역할을 한다.

        Question.object => Question = Django Class// objects = ORM

        Question_list => QuerySet, 리스트와 구조는 같지만 파이썬 기본 자료구조가 아니라 변환을 해야함. 리스트의 안의 타입은 dict
    """
    page = request.GET.get('page', '1')  # Get 으로 요청이 왔을 때 default 1 페이지 get('page', '1')에서 get 은 dict 의 key 값을 불러오는 함수, ('key', '존재하지 않으면 출력할 값 ) 을 의미
    kw = request.GET.get('kw', '')  # 검색어
    question_list = Question.objects.order_by('-create_date')  # order_by=> 조회 결과를 정렬, -create_date 에서 - 는 역순 정렬을 의미함.
    # print(Question.objects.values()[0].__class__, Question.objects.all(), question_list)

    """ 
        Q 함수는 논리연산자로 데이터를 조회하기 위해 사용하는 함수이다. 
        & (AND), | (OR), ~ (NOT)
        distinct 는 조회 결과에 중복이 있을 경우 중복을 제거하여 리턴하는 함수.
        POST 가 아닌 GET 방식.
        
        __ 의 의미는 관계를 지정하는데 사용 
        ex) answer__author__username => answer 모델의 author 필드를 통해 연결된 모델의 username 필드
        현재 question 이 없는 이유는 question_list 가 이미 quetion 모델에 접근했기 때문
        
        icontains : 대소문자를 구분하지 않고 포함하는지 확인
        iexact : 대소문자를 구분하지 않고 정확히 일치하는지 확인
        isnull : null 여부를 확인 
        등등 다양한 필터링 옵션을 제공
    """

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(comment__author__username__icontains=kw) |    # 댓글 작성자
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw) |  # 답변 글쓴이 검색
            Q(comment__content__icontains=kw)
        ).distinct()    # distinct => 중복제거

    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    # print(len(question_list))
    # print(type(paginator))
    page_obj = paginator.get_page(page)  # 데이터 전체를 조회하지 않고 해당 페이지의 데이터만 조회하게 됨.
    # print(paginator.count, paginator.num_pages, paginator.page_range, page_obj.next_page_number())
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)  # 없는 데이터를 요청 할 경우 500 페이지 대신 404 페이지를 출력. pk => primary key
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import CommentForm
from ..models import Question, Comment, Answer


@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    """
    pybo 질문댓글등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)

        # 어떤 에러가 발생했는지 보여줌
        error_messages = '\n'.join([f"{field}: {', '.join(errors)}" for field, errors in form.errors.items()])
        print(error_messages)
        print(form.errors, form.errors.items(), form.errors.keys(), form.errors.values())

        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user   # 댓글 작성자 = 요청자 ( 로그인한 사람 )
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = CommentForm()
    context = {'form': form}

    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    """
    pybo 질문댓글수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('pybo:detail', question_id=comment.question.id)
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    """
    pybo 질문댓글삭제
    """

    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.question.id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.question.id)


@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    """
    pybo 답글댓글등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    """
    pybo 답글댓글수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.answer.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    """
    pybo 답글댓글삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.answer.question.id)

templates/pybo/answer_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/comment_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
 <!-- unordered list 순서가 없는 리스트 // list 라서 for 문으로 나열 -->
 <!-- li list item  --> <!-- <a> 앵커 요소 링크 이동  -->
 <!-- h1 글씨 크기 1~5 작은게 제일 큼  -->
 <!-- 클래스에 대한 각종 데이터는 점프 투 장고 참고  -->
 <!-- https://miaow-miaow.tistory.com/48 form 에 대한 설명 -->
{% extends 'base.html' %}   <!-- base.html 을 확장 -->
{% block content %}
 <!--{% load static %}-->
<!--<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">-->
<div class="container my-3">
       <!-- message 표시 -->
    {% if messages %}  <!-- from django.contrib import messages 에서 제공 (message.error) -->
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                    <div class="badge bg-light text-dark p-2 text-start mx-3">
                        <div class="mb-2">modified at</div>
                        <div>{{ question.modify_date }}</div>
                    </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
                </div>
            </div>
            {% if question.file %}
                <div class="col-12 text-right">
                    <span>첨부파일 :&nbsp;</span>
                    <a href="{% url 'pybo:question_file_download' question.id %}" >{{ question.filename|truncatechars:25 }}</a> <!-- truncatechars 문자열 길이 설정-->
                </div>
            {% endif %}
            <!-- 질문 수정 삭제 -->
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'pybo:question_vote' question.id  %}" class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{question.voter.count}}</span>
                </a>
                {% if request.user == question.author %}
                <a href="{%url 'pybo:question_modify' question.id %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>

                <!-- "javascript:void(0)" : 링크를 클릭해도 동작하지 않게함 -->
                <!-- data-uri 는 url 을 저장하여 javascript 에서 사용하게 함.-->
                <!-- url 을 직접 사용하지 않는 이유는 "정말로 삭제하시겠습니까?" 확인 창을 실행한뒤에 url로 이동하게 하기 위해서-->
                <a href="javascript:void(0)"
                   class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'pybo:question_delete' question.id  %}">삭제</a>

                {% endif %}
            </div>


            <!-- 질문 댓글 Start -->
            <!-- Comment 모델이 Question 모델을 ForeignKey 로 참조하고 있으면, Django 는 기본적으로 comment_set 이라는 역참조 속성을 제공
                 ex) 해당 질문에 연결된 모든 댓글들을 가져올 수 있음. question.comment_set.all()-->
            {% if question.comment_set.count > 0 %}
            <div class="mt-3">
                {% for comment in question.comment_set.all %}  <!-- 등록한 댓글을 출력 -->
                    <div class="comment py-2 text-muted">  <!-- 댓글 각각에 comment 스타일 지정 -->
                        <span style="white-space: pre-line;">{{ comment.content }}</span>   <!-- 댓글내용 -->
                        <span>
                            - {{ comment.author }}, {{ comment.create_date }}   <!-- 작성자, 생성날짜-->
                            {% if comment.modify_date %}
                            (수정:{{ comment.modify_date }})  <!-- 수정 날짜 -->
                            {% endif %}
                        </span>
                        {% if request.user == comment.author %}
                        <a href="{% url 'pybo:comment_modify_question' comment.id  %}" class="small">수정</a>,
                        <!-- href="#" 링크가 클릭되었을때 자바스크립트 이벤트를 실행시키기 위한 빈 링크 역할-->
                        <a href="#" class="small delete"
                           data-uri="{% url 'pybo:comment_delete_question' comment.id  %}">삭제</a>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
            {% endif %}
            <div>
                <a href="{% url 'pybo:comment_create_question' question.id  %}"
                   class="small"><small>댓글 추가 ..</small></a>  <!-- 댓글 추가 링크 -->
            </div>
            <!-- 질문 댓글 End -->


        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                    <div class="badge bg-light text-dark p-2 text-start mx-3">
                        <div class="mb-2">modified at</div>
                        <div>{{ answer.modify_date }}</div>
                    </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            <!-- 답변 수정 삭제 -->
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'pybo:answer_vote' answer.id  %}"
                    class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{answer.voter.count}}</span>
                </a>
                {% if request.user == answer.author %}
                <a href="{% url 'pybo:answer_modify' answer.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                   data-uri="{% url 'pybo:answer_delete' answer.id  %}">삭제</a>
                {% endif %}
            </div>

             {% if answer.comment_set.count > 0 %}
                <div class="mt-3">
                    {% for comment in answer.comment_set.all %}
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author }}, {{ comment.create_date }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'pybo:comment_modify_answer' comment.id  %}" class="small">수정</a>,
                            <a href="#" class="small delete"
                               data-uri="{% url 'pybo:comment_delete_answer' comment.id  %}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
        {% endif %}
        <div>
            <a href="{% url 'pybo:comment_create_answer' answer.id  %}"
               class="small"><small>댓글 추가 ..</small></a>
        </div>


        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류 표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류 표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
                      name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
 <!-- 질문을 삭제할 수 있는 자바스크립트-->
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});

const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <!-- 파일이나 이미지 같은 바이너리 데이터를 전송할 때 multipart/form-data 사용-->
    <!-- enctype : encoding type => 폼 데이터가 서버로 전송될 떄 어떤 방식으로 데이터를 인코딩할지 정의   -->
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% include "form_errors.html" %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <div class="card-footer">
            <div class="form-group">
            {{ form.file }}
            <small id="help" class="form-text text-muted">
                [파일 업로드]&nbsp;첨부할 파일을 업로드 해주세요. 여러 파일은 압축해서 업로드해주세요.
                <!--&nbsp; 일반 공백 문자와 다른 공백 (여러 개의 공백으로 인식)-->
            </small>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

{% block script %}

<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function() {
    var fileLink = document.querySelector('.card-footer a'); // card-footer class 의 <a> 태그 선택 form.file 에서 파일이 존재하면 <a> 자동생성됨
    var filename = "{{ form.filename.value|default_if_none:'' }}";

    if (fileLink) {
        fileLink.textContent = filename; // 태그에 보여지는 text 변경

        fileLink.addEventListener('click', function(event) {
            event.preventDefault(); // 기본 동작을 막음 (이 경우, 링크의 이동을 막음)
        });
    }
});
</script>

{% endblock %}