common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

"""
django.contrib.auth -   사용자 관리, 권한 부여, 세션 관리 등 보안과 인증 기능을 제공.
                        1.사용자 관리(User Management): 
                        사용자 생성, 삭제, 변경 등의 기능을 제공.
                        User 모델을 제공하여 기본적인 사용자 정보를 저장. (현재 forms.py 에서 사용)
                        2.인증(Authentication):
                        사용자 로그인, 로그아웃, 세션 관리 등 사용자 인증을 다룸. - 세션 관리 : 웹사이트를 이용하는 동안 일시적으로 정보를 저장 관리 하는것.
                        사용자 인증을 위한 기본적인 뷰와 폼을 제공.
                        3.권한과 그룹(Permissions and Groups):
                        사용자에 대한 권한을 관리하고 그룹화할 수 있는 기능을 제공.
                        사용자에게 특정 권한을 부여하여 특정 기능에 접근을 제한할 수 있습니다.
                        4.비밀번호 관리(Password Management):                    
                        비밀번호 변경, 초기 비밀번호 설정, 비밀번호 재설정 등 비밀번호 관련 기능을 제공.
                        비밀번호 해싱과 같은 보안 관련 기능을 처리. 
"""
app_name = 'common'

urlpatterns = [

    # login, logout 뷰를 따로 만들 필요없이 장고에서 제공하는 django.contrib.auth 앱을 사용
    # 로그인 성공하면 django.contrib.auth 패키지는 디폴트로 /account/profile/ 이라는 url로 이동시켜서 settings에 완료후 url 을 '/' 로 설정함.
    # 로그아웃도 마찬가지로 디폴트로 이동하는 url 이 있어서 따로 설정함.

    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),  # LoginView가 common 디렉터리의 템플릿을 참조
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import messages
from django.shortcuts import redirect


def protected_file(request, path, document_root=None):
    messages.error(request, "접근 불가")
    print(request)
    return redirect('/')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

# if settings.DEBUG:
#     # 개발 서버로 실행 중 일떄 설정된 곳으로 접근하는 요청을 처리하기 위한 설정 // 미디어 파일을 로컬 pc 에 저장할 수 있고 직접 관리, 접근할 수 있으면 사용하지 않아도 무관함,
#     urlpatterns += static(settings.MEDIA_URL, protected_file, document_root=settings.MEDIA_ROOT)  # media 경로 추가 // 사용자가 업로드한 파일들을 개발 서버에서 확인할 수 있게 해줌
#     # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # media 경로 추가 // 사용자가 업로드한 파일들을 개발 서버에서 확인할 수 있게 해줌

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views

app_name = 'pybo'  # pybo 앱 이외의 다른 앱이 프로젝트에 추가 될 때, 동일한 url 별칭을 사용하지 않기 위한 방법
urlpatterns = [
    # base_views.py
    path('',
         base_views.index, name='index'),
    path('<int:question_id>/',
         base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/',
         question_views.question_vote, name='question_vote'),
    path('question/download/<int:question_id>/',
         question_views.question_file_download, name='question_file_download'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/',
         answer_views.answer_vote, name='answer_vote'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/',
         comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
         comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
         comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/',
         comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/',
         comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/',
         comment_views.comment_delete_answer, name='comment_delete_answer'),
]

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from ..models import Question


def index(request):
    """
        ORM (Object-Relational Mapping) => Django Class 와 Database Data 를 연결 해주는 것 즉 Question.objects 에서 objects 가 연결해주는 역할을 한다.

        Question.object => Question = Django Class// objects = ORM

        Question_list => QuerySet, 리스트와 구조는 같지만 파이썬 기본 자료구조가 아니라 변환을 해야함. 리스트의 안의 타입은 dict
    """
    page = request.GET.get('page', '1')  # Get 으로 요청이 왔을 때 default 1 페이지 get('page', '1')에서 get 은 dict 의 key 값을 불러오는 함수, ('key', '존재하지 않으면 출력할 값 ) 을 의미
    kw = request.GET.get('kw', '')  # 검색어
    question_list = Question.objects.order_by('-create_date')  # order_by=> 조회 결과를 정렬, -create_date 에서 - 는 역순 정렬을 의미함.
    # print(Question.objects.values()[0].__class__, Question.objects.all(), question_list)

    """ 
        Q 함수는 논리연산자로 데이터를 조회하기 위해 사용하는 함수이다. 
        & (AND), | (OR), ~ (NOT)
        distinct 는 조회 결과에 중복이 있을 경우 중복을 제거하여 리턴하는 함수.
        POST 가 아닌 GET 방식.
        
        __ 의 의미는 관계를 지정하는데 사용 
        ex) answer__author__username => answer 모델의 author 필드를 통해 연결된 모델의 username 필드
        현재 question 이 없는 이유는 question_list 가 이미 quetion 모델에 접근했기 때문
        
        icontains : 대소문자를 구분하지 않고 포함하는지 확인
        iexact : 대소문자를 구분하지 않고 정확히 일치하는지 확인
        isnull : null 여부를 확인 
        등등 다양한 필터링 옵션을 제공
    """

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(comment__author__username__icontains=kw) |    # 댓글 작성자
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw) |  # 답변 글쓴이 검색
            Q(comment__content__icontains=kw)
        ).distinct()    # distinct => 중복제거

    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    # print(len(question_list))
    # print(type(paginator))
    page_obj = paginator.get_page(page)  # 데이터 전체를 조회하지 않고 해당 페이지의 데이터만 조회하게 됨.
    # print(paginator.count, paginator.num_pages, paginator.page_range, page_obj.next_page_number())
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)  # 없는 데이터를 요청 할 경우 500 페이지 대신 404 페이지를 출력. pk => primary key
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 : 사용자가 입력한 필드 값에 대한 오류로 값이 누락되었거나 필드의 형식이 일치하지 않는 경우에 발생 ( 이메일 형식이 이상할 때 )-->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 : 필드의 값과는 상관없이 다른 이유로 발생하는 오류 (비밀번호, 비밀번호 확인 필드가 서로 일치하지 않을 때)-->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <!-- view 에서 템플릿에 user 객체를 전달하지 않아도 django.contrib.auth 기능으로 user 객체 사용 가능, 사용자가 로그인 되었는지를 판별 -->
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                        <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>